### ISSUE TITLE
源码更新20201015后编译失败

### ISSUE THREAD

**Issue by yguangg** [chongshengB/Padavan-build#190]
源码更新20201015后编译失败

**Comment by yguangg** [comment]
错误信息：
Check failure on line 1 in .github

@github-actions
github-actions
/ build

.github#L1
Process completed with exit code 2.

**Comment by wuerone** [comment]
Check failure on line 1 in .github

@github-actions
github-actions
/ build

.github#L1
Process completed with exit code 2.
 Check warning on line 1 in .github

@github-actions
github-actions
/ build

.github#L1
No files were found with the provided path: /opt/images. No artifacts will be uploaded.

**Comment by one02free** [comment]
编译失败+1

**Comment by ssrubsd** [comment]
+1

**Comment by i6941** [comment]
编译失败+1

**Comment by TabrisKing** [comment]
+1 无法正常编译，报错如上

**Comment by bunimeidefan** [comment]
加1

**Comment by friendmz** [comment]
加1，报错如上

**Comment by jiaojiaowoai** [comment]
Check failure on line 1 in .github

@github-actions github-actions / build

.github#L1

Process completed with exit code 2.

Check warning on line 1 in .github

@github-actions github-actions / build

.github#L1

No files were found with the provided path: /opt/images. No artifacts will be uploaded.

**Comment by ppokwsx** [comment]
同报错
@github-actions github-actions / build

.github#L1

No files were found with the provided path: /opt/images. No artifacts will be uploaded.

**Comment by ppokwsx** [comment]
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make[1]: *** [go_build] Error 2
Makefile:34: recipe for target 'go_build' failed
make[1]: Leaving directory '/opt/rt-n56u/trunk/tools'
make: *** [tools] Error 2
Makefile:177: recipe for target 'tools' failed
Error: Process completed with exit code 2.

**Comment by JaysonPeng** [comment]
+

**Comment by JaysonPeng** [comment]
+1我也是
