### ISSUE TITLE
无法自动编译， Initialization environment 失败

### ISSUE THREAD

**Issue by JayXus** [chongshengB/Padavan-build#44]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-7/lib32asan4_7.4.0-1ubuntu1~18.04.1_amd64.deb  404  Not Found [IP: 52.177.174.250 80]
Fetched 19.1 MB in 3s (5465 kB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-7/libx32asan4_7.4.0-1ubuntu1~18.04.1_amd64.deb  404  Not Found [IP: 52.177.174.250 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-7/lib32ubsan0_7.4.0-1ubuntu1~18.04.1_amd64.deb  404  Not Found [IP: 52.177.174.250 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-7/libx32ubsan0_7.4.0-1ubuntu1~18.04.1_amd64.deb  404  Not Found [IP: 52.177.174.250 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-7/lib32cilkrts5_7.4.0-1ubuntu1~18.04.1_amd64.deb  404  Not Found [IP: 52.177.174.250 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-7/libx32cilkrts5_7.4.0-1ubuntu1~18.04.1_amd64.deb  404  Not Found [IP: 52.177.174.250 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-8/lib32mpx2_8.3.0-6ubuntu1~18.04.1_amd64.deb  404  Not Found [IP: 52.177.174.250 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-7/lib32gcc-7-dev_7.4.0-1ubuntu1~18.04.1_amd64.deb  404  Not Found [IP: 52.177.174.250 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-7/libx32gcc-7-dev_7.4.0-1ubuntu1~18.04.1_amd64.deb  404  Not Found [IP: 52.177.174.250 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/g/gcc-7/gcc-7-multilib_7.4.0-1ubuntu1~18.04.1_amd64.deb  404  Not Found [IP: 52.177.174.250 80]

**Comment by chongshengB** [comment]
已修复
